{"score": 70, "full_score": 100, "tests": {"docker_build_run": "PASS (10/10)", "run_docker_autograde": "PASS (0/0)", "protobuf_interface": "PASS (10/10)", "set_coefs": "PASS (10/10)", "predict": "Traceback (most recent call last):\n  File \"/autograde/tester.py\", line 32, in run\n    result = self.func()\n             ^^^^^^^^^^^\n  File \"/autograde/docker_autograde.py\", line 28, in wrapper\n    return test_func(stub)\n           ^^^^^^^^^^^^^^^\n  File \"/autograde/docker_autograde.py\", line 132, in predict\n    assert re.match(r\"^y: 0.9663\\d+\\n$\", str(response)), response\nAssertionError: y: 0.9663\n\n", "predict_single_call_cache": "PASS (10/10)", "predict_full_cache_eviction": "Traceback (most recent call last):\n  File \"/autograde/tester.py\", line 32, in run\n    result = self.func()\n             ^^^^^^^^^^^\n  File \"/autograde/docker_autograde.py\", line 28, in wrapper\n    return test_func(stub)\n           ^^^^^^^^^^^^^^^\n  File \"/autograde/docker_autograde.py\", line 155, in predict_full_cache_eviction\n    response = stub.Predict(PredictRequest(X=[3, 2, i]))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/dist-packages/grpc/_channel.py\", line 1161, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/dist-packages/grpc/_channel.py\", line 1004, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNKNOWN\n\tdetails = \"Exception calling application: bad argument type for built-in operation\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {created_time:\"2023-10-14T20:12:25.438599407+00:00\", grpc_status:2, grpc_message:\"Exception calling application: bad argument type for built-in operation\"}\"\n>\n", "set_coefs_cache_invalidation": "PASS (10/10)", "client_workload_1": "PASS (10/10)", "client_workload_2": "Traceback (most recent call last):\n  File \"/autograde/tester.py\", line 32, in run\n    result = self.func()\n             ^^^^^^^^^^^\n  File \"/autograde/docker_autograde.py\", line 56, in wrapper\n    return test_func(hit_rate)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/autograde/docker_autograde.py\", line 192, in client_workload_2\n    assert expected_hit_rate == hit_rate, (\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAssertionError: Expected cache hit rate to be 0.16666666666666666, but got 0.09090909090909091\n", "client_workload_3": "PASS (10/10)"}}