{"score": 10, "full_score": 100, "tests": {"docker_build_run": "PASS (10/10)", "run_docker_autograde": ["Traceback (most recent call last):\n", "  File \"/home/caseyreyes/project-3-perrito_p3/tester.py\", line 32, in run\n    result = self.func()\n", "  File \"/home/caseyreyes/project-3-perrito_p3/autograde.py\", line 49, in run_docker_autograde\n    check_output(\n", "  File \"/usr/lib/python3.10/subprocess.py\", line 421, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n", "  File \"/usr/lib/python3.10/subprocess.py\", line 526, in run\n    raise CalledProcessError(retcode, process.args,\n", "subprocess.CalledProcessError: Command '['docker', 'exec', 'p3_autograde', 'python3', 'docker_autograde.py']' returned non-zero exit status 1.\n"], "protobuf_interface": "FAIL: docker_test.json not found", "set_coefs": "FAIL: docker_test.json not found", "predict": "FAIL: docker_test.json not found", "predict_single_call_cache": "FAIL: docker_test.json not found", "predict_full_cache_eviction": "FAIL: docker_test.json not found", "set_coefs_cache_invalidation": "FAIL: docker_test.json not found", "client_workload_1": "FAIL: docker_test.json not found", "client_workload_2": "FAIL: docker_test.json not found", "client_workload_3": "FAIL: docker_test.json not found"}}